 vector<int> findUnion(int arr1[], int arr2[], int n, int m)
    {
       int i=0,j=0,last_elem=-65343;
       vector<int>Union;
       while(i<n && j<m)
       {
           if(arr1[i]<arr2[j])
           {
               if(arr1[i]!=last_elem)
               {
               Union.push_back(arr1[i]);
               last_elem=arr1[i];
               i++;
               }
               else
               {
                   i++;
               }
           }
          else if (arr1[i]==arr2[j])
          {
              if(arr1[i]!=last_elem)
              {
                  Union.push_back(arr1[i]);
                  last_elem=arr1[i];
                  i++;
                  j++;
              }
              else{
                  i++;
                  j++;
              }
          }
           else
           {
               if(arr2[j]!=last_elem)
               {
               Union.push_back(arr2[j]);
               last_elem=arr2[j];
               j++;
               }
               else
               {
                   j++;
               }
           }
       }
       while(i<n)
       {
           if(arr1[i]!=last_elem)
           {
            Union.push_back(arr1[i]);
            last_elem=arr1[i];
            i++;
           }
           else
           {
               i++;
           }
       }
       while(j<m)
       {
           if(arr2[j]!=last_elem)
           {
            Union.push_back(arr2[j]);
            last_elem=arr2[j];
            j++;
           }
           else
           {
               j++;
           }
       }
       return Union;
    }